# Generated by Django 4.0.5 on 2022-06-22 03:40

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('payroll_code', models.CharField(blank=True, max_length=3, null=True)),
                ('badge_prefix', models.CharField(blank=True, max_length=3, null=True)),
                ('new_development', models.BooleanField(default=False)),
                ('currently_supported', models.BooleanField(default=False)),
                ('address_1', models.CharField(blank=True, max_length=128, null=True, verbose_name='address')),
                ('address_2', models.CharField(blank=True, max_length=128, null=True, verbose_name='address cont')),
                ('city', models.CharField(blank=True, max_length=64, null=True, verbose_name='city')),
                ('state', localflavor.us.models.USStateField(blank=True, max_length=2, null=True, verbose_name='state')),
                ('zip_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='zip code')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
